# Generated by repro: do not edit by hand
# Please edit Dockerfiles in .repro/
FROM rocker/verse:4.2.2
WORKDIR /home/rstudio
RUN apt-get update -y && apt-get install -y rsync
RUN tlmgr install collection-latexrecommended
RUN tlmgr install apa6 threeparttable endfloat framed was multirow threeparttablex environ trimspaces xpatch csquotes
RUN install2.r --error --skipinstalled \ 
  gert \ 
  ggpubr \ 
  here \ 
  lavaan \ 
  papaja \ 
  sessioninfo \ 
  SimDesign \ 
  tidyverse
RUN installGithub.r \ 
  aaronpeikert/repro@5a920f7
